linters:
  enable:
    - gofmt
    - revive
    - gocyclo
    - misspell
    - whitespace
    - goimports
    - gofmt

linters-settings:
  gocyclo:
    min-complexity: 8
  goimports:
    local-prefixes: github.com/articulate/ohdear-sdk
  gosimple:
    go: "1.17"
  staticcheck:
    go: "1.17"
  unused:
    go: "1.17"
